version: "3.9"

services:
  finanzauto-api:
    container_name: finanzauto-api
    build:
      context: .
      dockerfile: Finanzauto.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=finanzauto_db;Username=postgres;Password=postgres
    networks:
      - finanzauto-network

  postgres:
    image: postgres:15
    container_name: finanzauto-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finanzauto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finanzauto-network

volumes:
  postgres_data:

networks:
  finanzauto-network: